MKSHELL=mkx
FORMAT=markdown+grid_tables+table_captions+pipe_tables+example_lists+fenced_code_attributes+fenced_divs+bracketed_spans+footnotes
APA7=./apa.csl


help:QV: ## show this command
	pipeline {
		cmd/show-help mkfile
	}
	sort

%.t.html:Q:	%.md	%.json
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--data-dir /usr/share/pandoc/data
		--filter=pandoc-manubot-cite
		--citeproc
		-o ${target}
		${stem}.md

%.json:Q:
	mkvars
	if {
		stest -ve ${target}
	}
	tmpfile ${target}.build
	echo []

%.t.docx:Q:	%.md	%.json
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--data-dir /usr/share/pandoc/data
		--filter=pandoc-manubot-cite
		--citeproc
		-o ${target}
		${stem}.md

%.t.tex:Q:	%.md	%.json
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--data-dir /usr/share/pandoc/data
		--template ucha
		--filter=pandoc-manubot-cite
		--citeproc
		-o ${target}
		${stem}.md

%.t.pdf:Q:	%.md	%.json
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--data-dir /usr/share/pandoc/data
		--template ucha
		--filter=pandoc-manubot-cite
		--citeproc
		--pdf-engine=xelatex
		-o ${target}
		${stem}.md

%.p.tex:Q:	%.pmd	%.json
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--to beamer
		--slide-level=2
		--pdf-engine=lualatex
		--filter=pandoc-manubot-cite
		--citeproc
		-o ${target}
		${stem}.pmd

%.p.pptx:Q:	%.pmd	%.json
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--slide-level=2
		--pdf-engine=lualatex
		--filter=pandoc-manubot-cite
		--citeproc
		-o ${target}
		${stem}.pmd

%.p.pdf:Q:	%.pmd	%.json
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--to beamer
		--slide-level=2
		--pdf-engine=lualatex
		--filter=pandoc-manubot-cite
		--citeproc
		-o ${target}
		${stem}.pmd

tesis:VQ:	build/tesis.pdf ## build thesis file

build:Q:
	foreground {
		mkdir -p build
	}
	sudo mount -t tmpfs none build

build/tesis.pdf:Q:	build/tesis.tex
	mkvars
	debug
	latexmk
		-xelatex
		-outdir=build
		${prereq}

pvc:VQ:	preview	monitor	## launch monitor and preview

preview:VQ:	tesis	## thesis previsualization
	background {
		zathura build/tesis.pdf
	}

monitor:VQ:	## monitor changes in thesis files
	cmd/on-thesis-requirements-change
	mk build/tesis.pdf

build/tesis.tex:Q:	build	`{cmd/thesis-requirements}
	pipeline {
		cmd/thesis-content
	}
	xargs
	mkvars
	importas -i FORMAT FORMAT
	debug
	pandoc
		-f ${FORMAT}
		--data-dir /usr/share/pandoc/data
		--template ucha
		--standalone
		--filter=pandoc-manubot-cite
		--citeproc
		--pdf-engine=xelatex
		-o ${target}

clean:VQ: ## clean generated files
	foreground {
	pipeline {
		cmd/targets
	}
	xargs rm -f
	}
	foreground {
		sudo umount build
	}
	rmdir build
